### ISSUE TITLE
No sound

### ISSUE THREAD

**Issue by nightcat2005** [ivan-hc/OBS-Studio-appimage#10]
Hi.
I have Debian 11.9. I try use OBS-Studio-appimage, but Audio Capture Device (ALSA) not working. How to resolve this issue?
Here is the output LD_DEBUG=libs ./OBS-Studio_30.1.1-1-archimage3.4-x86_64.AppImage
[obs_log.txt](https://github.com/ivan-hc/OBS-Studio-appimage/files/15028940/obs_log.txt)

**Comment by ivan-hc** [comment]
At the end of [this workflow](https://github.com/ivan-hc/OBS-Studio-appimage/actions/runs/8743037836) download the AppImage again from [releases/latest](https://github.com/ivan-hc/OBS-Studio-appimage/releases/tag/continuous) and let me know

**Comment by nightcat2005** [comment]
Thank you very much. Everything is working now.
