### ISSUE TITLE
high cpu usage. 

### ISSUE THREAD

**Issue by Samueru-sama** [ivan-hc/OBS-Studio-appimage#11]
I noticed that this appimage is using 30% of my 20 thread CPU by just having obs open not recording. 

![image](https://github.com/ivan-hc/OBS-Studio-appimage/assets/36420837/0314d95f-7f96-4a5f-bb5e-c6556a47b529)

I tested disabling the preview and it didn't help.

**Comment by ivan-hc** [comment]
If you asked me this its because this behaviour is not normal, isn't it? I'm not an OBS user, so I don't know.

**Comment by Samueru-sama** [comment]
> If you asked me this its because this behaviour is not normal, isn't it? I'm not an OBS user, so I don't know.

With the native arch package the cpu usage with obs open is 1%

I also made a crude obs-appimage using the ubuntu ppa, the appimage only works on the ubuntu container that I have, but if I open it there it also only uses 1% cpu.

**Comment by ivan-hc** [comment]
I've a AMD Ryzen 5 3600, just 3,5% in idle

**Comment by ivan-hc** [comment]
however, note that archimage is a arch linux container into an appimage, so its not just obs the program that is unning, also bwrap is involved (it is into tha appimage), and maybe other processes to made the container work

**Comment by Samueru-sama** [comment]
> I've a AMD Ryzen 5 3600, OBS is just 3,5% in idle

I have a xeon e5 2640 v4. I normally never see this level of cpu usage when doing anything but compiling. 

The problem might be distro specific. Will test on other distros and get back. 

Worth mentioning that this does not happen on gimp or other archimages you have.

**Comment by Samueru-sama** [comment]
Alright I tested on a fedora live environment, same issue. 

The issue happens when I enable the screen capture source but I am not recording. Without it the cpu usage is only "8%" which is still very high. 

I wonder if there is a race condition going on.

**Comment by Samueru-sama** [comment]
The issue went away on its own lol 

![image](https://github.com/user-attachments/assets/d8ca73c5-52ac-4336-94d3-39993e212cda)
