### ISSUE TITLE
The problem with executing this script

### ISSUE THREAD

**Issue by Drsheppard01** [ivan-hc/OBS-Studio-appimage#2]
```
Cannot move './libunionpreload.so' to './obs-studio/obs-studio.AppDir/': This is not the directory
obs-build: line 64: ./obs-studio/obs-studio.AppDir/AppRun:  There is no such file or directory
chmod: Cannot access to './obs-studio/obs-studio.AppDir/AppRun': There is no such file or directory
appimagetool, continuous build (commit 5735cc5), build <local dev build> built on 2023-03-08 22:52:04 UTC
Error: no such file or directory: ./obs-studio/obs-studio.AppDir
mkdir: it is impossible to create a directory «version»: The file exists
mv: failed stat for './tmp/*.AppImage': There is no such file or directory
```

**Comment by ivan-hc** [comment]
strange, this works for my, I'm on Debian

**Comment by ivan-hc** [comment]
however don't worry, man, I can dedicate hours in testing this script on my machine, the final goal is to put it into a GH action so it will build a distributable Appimage for everybody. I only need to understand what does not work and step-by-step I'm solving a lot of issues. I started this script about 1 year and a half ago and the issues were a lot more, before.

**Comment by ivan-hc** [comment]
@Drsheppard01 if you wish to test the Appimage it is available for download as a pre-build https://github.com/ivan-hc/OBS-Studio-appimage/releases/tag/continuous you can't still use it normally
