### ISSUE TITLE
please merge language , some language is empty

### ISSUE THREAD

**Issue by newyorkthink** [ivan-hc/OBS-Studio-appimage#3]
![image](https://github.com/ivan-hc/OBS-Studio-appimage/assets/87791643/58e0c892-ca36-4de2-9249-825de7c17714)

**Comment by newyorkthink** [comment]
some language it show '[] [] [] []'

**Comment by ivan-hc** [comment]
This AppImage of OBS Studio is based on JuNest, a minimal Arch Linux distribution, so to build it I use "pacman", the 'package manager of Arch Linux. Are Chinese/Japanese/other languages in separate packages?

**Comment by newyorkthink** [comment]
yes, chinese and japanese have different packages
the chinsese use this:
pacman -Syu adobe-source-han-serif-cn-fonts wqy-zenhei --noconfirm

**Comment by newyorkthink** [comment]
but i don't know Japanese use package

**Comment by ivan-hc** [comment]
By installing the adobe packages the final AppImage is about 900 MB... so this is not a good idea.

Anyway, just found that by adding the flag `--bind=/usr/share/fonts` in the AppRun, I can read all the missing fonts, so this is the way. You can already test this by extracting the AppImage with the command `./*AppImage --appimage-extract` and by replacing the last line in the AppRun with this one:

    $HERE/.local/share/junest/bin/junest proot -n -b "--bind=/home --bind=/home/$(echo $USER) --bind=/media --bind=/opt --bind=/etc --bind=/usr/share/fonts" 2> /dev/null -- $APP "$@"

I'll correct this feature soon, but first I want to check a solution to automatically add the locale without having to set it first :)

**Comment by ivan-hc** [comment]
The problem with fonts has been solved. Also added automatic detection of locales from the host (I think you should remove OBS's configuration files to see the change).

Just wait the time that GH Actions has finisced and you're ready.
