### ISSUE TITLE
qt.qpa.plugin: Could not find the Qt platform plugin "wayland" in

### ISSUE THREAD

**Issue by Prisoner709** [ivan-hc/OBS-Studio-appimage#4]
Ciao, i have the problem mentioned in this package. Qt5 plugin for wayland is installed. This terminal command resolve the problem: QT_QPA_PLATFORM=xcb obs-studio. I have tryed to insert this command in the Exec= line of the .desktop file, but i can't do it without losing the launcher in Gnome. How can I solve the problem? Or is it a problem that you can solve with an appimage update? Grazie.

**Comment by ivan-hc** [comment]
```
Exec=sh -c 'QT_QPA_PLATFORM=xcb obs-studio'
```
this should be the correct syntax in .desktop files

**Comment by Prisoner709** [comment]
Grazie, the syntax work.
