### ISSUE TITLE
Running the appimage creates a ~/.cache dir. 

### ISSUE THREAD

**Issue by Samueru-sama** [ivan-hc/OBS-Studio-appimage#6]
I have XDG_CACHE_HOME="$HOME/.local/cache" which means I don't have a $HOME/.cache dir on my system. 

Running this appimage results in that directory being created, with this file inside named just_wrapper.old: 

```
#!/usr/bin/env bash

eval "junest_args_array=(${JUNEST_ARGS:-ns})"
junest "${junest_args_array[@]}" -- $(basename ${0}) "$@"
```

This is likely created by a hardcoded path to cache instead of checking for the xdg variables. Should be an easy fix.

**Comment by ivan-hc** [comment]
Yes, you're right, this was what remains of my old tests, when it was difficult to bypass JuNest's checks, the earlier days.

I'll remove that line from the AppRun to fix this... just rebuilt on my PC and seen that we don't need this anymore.
