### ISSUE TITLE
App Fails to Launch unless I create the directory /media

### ISSUE THREAD

**Issue by d-air1** [ivan-hc/OBS-Studio-appimage#7]
I have tried both your obs appimage as well ass your handbrake one and one thing I noticed is that they will fail to launch with the error message `bwrap: Can't find source path /media: No such file or directory`. If I create that directory then everything works fine. Any reason it is looking for a non default directory?

P.S.: thanks for the cool project.

**Comment by ivan-hc** [comment]
Yes, the app runs into a container into an AppImage, many distributions (nomrally those based on systemd) have /mnt and /media in the root to mount external drives. I'm not sure on how many distros have not a /media directory in the root of the file system. What is your?

**Comment by ivan-hc** [comment]
I've moved /media as an optional directory, if it does not exists, the next release will work without it

**Comment by d-air1** [comment]
Ok, thanks that was quick. As for my distro, I am on EndeavourOS / Arch. I was under the impression that most distros had moved to using /run/media/your-username/ as the default directory for mounting external drives.

**Comment by d-air1** [comment]
I found the reference I was looking for in the arch wiki. Any program, distro that uses udisks2 to mount will auto mount in /run/media/[your username]. I think this is one of the paths you should be looking for. 
![Screenshot_20240220_205951](https://github.com/ivan-hc/OBS-Studio-appimage/assets/40647198/29dd67fa-08eb-4f5a-892f-7fed513f9777)

**Comment by d-air1** [comment]
As you can see by this screenshot from the relevant section in the arch wiki. Reverting to the older /media directory would require people to setup their own udev rule.

**Comment by ivan-hc** [comment]
I'm patching all my Archimages right now, in case they have the same issue, just reinstall from the next update.

For now I've started workflows for obs, handbrake and spacedadet. Normally I've not this kind of feedback.

**Comment by d-air1** [comment]
I have already download the build you released about 20 minutes ago and it works. Thanks for such a fast resolution.
