### ISSUE TITLE
QT Platform plugin not found

### ISSUE THREAD

**Issue by fiftydinar** [ivan-hc/OBS-Studio-appimage#8]
```
qt.qpa.plugin: Could not find the Qt platform plugin "wayland" in ""
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vkkhrdisplay, vnc, xcb.
```

Fedora Silverblue 39

Is this AppImage tested on Gnome? I guess it tries to use host qt libraries, but Gnome doesn't have them, so it fails to run.

**Comment by ivan-hc** [comment]
No, I've not tested it on Wayland, also because I have issues with it on Virtualbox.

If you can provide me more tests to improve the AppImage, I would be grateful.

You can start by compiling it on your system.

If you've understand how Archimage works, you should be able to add missing plugins in $DEPENDENCES or scan for missing libraries in $LIBSAVED. The workflow in the script will redirect you on the right way. Thank you.

**Comment by fiftydinar** [comment]
qt6-wayland dependency is already installed.

I tried to set `QT_QPA_PLATFORM=wayland` environment variable, that doesn't work.

But when I set `QT_QPA_PLATFORM=xcb` (x11), it launches successfully.

**Comment by ivan-hc** [comment]
Let me try with this environment variable on X11, maybe I can export that by default

**Comment by fiftydinar** [comment]
I think that is necessary for all your other QT AppImages too, as they also don't launch on my system for this same reason.

**Comment by ivan-hc** [comment]
retry the build from releases when this workflow run has finished

https://github.com/ivan-hc/OBS-Studio-appimage/actions/runs/8095863642

**Comment by fiftydinar** [comment]
qBitTorrent launches successfully, but still has that error in logs. So QT_QPA_PLATFORM=xcb is needed for that too.

On VLC, it makes no difference.

**Comment by fiftydinar** [comment]
> > I think that is necessary for all your other QT AppImages too, as they also don't launch on my system for this same reason.
> 
> Let we see if it works for you, and if so, I'll change everything you say.
> 
> Can you redirect me on my QT apps, I've lost the count :S
> 
> OBS, qbittorrent... then?
> 
> EDIT: ...VLC. Then they are only 3

This one launches successfully without any modifications. Just download and run!

**Comment by ivan-hc** [comment]
Yes, I've already tested it when ready (its my son, after all :P )
